apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-webservice-default" .Release.Name }}
spec:
  hostnames:
    {{- toYaml .Values.httpRoute.webservice.hostnames | nindent 4 }}
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  rules:
    - backendRefs:
      - group: ''	
        kind: Service
        name: {{ printf "%s-webservice-default" .Release.Name }}
        port: 8181
        weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
