apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argo-cd
spec:
  destination:
    namespace: headlamp
    server: https://kubernetes.default.svc
  project: home-server
  source:
    path: charts/headlamp
    repoURL: https://gitlab.nwallace.io/home-server/home-server-helm.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: headlamp
      jsonPointers:
        - /spec/rules/0/backendRefs/0/group
        - /spec/rules/0/backendRefs/0/kind
        - /spec/rules/0/backendRefs/0/weight