apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aoc-apply-bot
  namespace: death-and-taxes
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/aoc-apply-bot
      sourceRef:
        kind: GitRepository
        name: home-server
        namespace: home-server
      reconcileStrategy: Revision
  driftDetection:
    mode: enabled
