apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-internal
  annotations:
    external-dns.alpha.kubernetes.io/controller: hacktonotmanagethesehostswithexternaldns
spec:
  hostnames:
    {{- toYaml .Values.httpRoute.internal.hostnames | nindent 4 }}
  parentRefs:
    {{- toYaml .Values.httpRoute.internal.parentRefs | nindent 4 }}
  rules:
    - backendRefs:
        - group: ''	
          kind: Service
          name: {{ .Release.Name }}
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
