apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-external
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  addresses:
  - type: IPAddress
    value: 192.168.2.16
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: https
    hostname: "*.nwallace.io"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: nwallace.io-external-tls-secret
  - allowedRoutes:
      namespaces:
        from: All
    name: http
    port: 80
    protocol: HTTP