apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}
spec:
  hostnames:
    {{- toYaml .Values.httpRoute.web.hostnames | nindent 4 }}
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ .Release.Name }}
          port: 9001
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
