apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}
spec:
  hostnames:
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  rules:
    - filters:
      - type: RequestRedirect
        requestRedirect:
          hostname: "github.com"
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: "/nwallace83"
          statusCode: 301
      matches:	
        - path:	
            type: PathPrefix	
            value: /